import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidv4 } from "uuid";

const chileData = {
	regions: [
		{
			city: "Arica y Parinacota",
			districts: ["Arica", "Camarones", "Putre", "General Lagos"],
		},
		{
			city: "Tarapacá",
			districts: [
				"Iquique",
				"Alto Hospicio",
				"Pozo Almonte",
				"Camiña",
				"Colchane",
				"Huara",
				"Pica",
			],
		},
		{
			city: "Antofagasta",
			districts: [
				"Antofagasta",
				"Mejillones",
				"Sierra Gorda",
				"Taltal",
				"Calama",
				"Ollagüe",
				"San Pedro de Atacama",
				"Tocopilla",
				"María Elena",
			],
		},
		{
			city: "Atacama",
			districts: [
				"Copiapó",
				"Caldera",
				"Tierra Amarilla",
				"Chañaral",
				"Diego de Almagro",
				"Vallenar",
				"Alto del Carmen",
				"Freirina",
				"Huasco",
			],
		},
		{
			city: "Coquimbo",
			districts: [
				"La Serena",
				"Coquimbo",
				"Andacollo",
				"La Higuera",
				"Paiguano",
				"Vicuña",
				"Illapel",
				"Canela",
				"Los Vilos",
				"Salamanca",
				"Ovalle",
				"Combarbalá",
				"Monte Patria",
				"Punitaqui",
				"Río Hurtado",
			],
		},
		{
			city: "Valparaíso",
			districts: [
				"Valparaíso",
				"Casablanca",
				"Concón",
				"Juan Fernández",
				"Puchuncaví",
				"Quintero",
				"Viña del Mar",
				"Isla de Pascua",
				"Los Andes",
				"Calle Larga",
				"Rinconada",
				"San Esteban",
				"La Ligua",
				"Cabildo",
				"Papudo",
				"Petorca",
				"Zapallar",
				"Quillota",
				"Calera",
				"Hijuelas",
				"La Cruz",
				"Nogales",
				"San Antonio",
				"Algarrobo",
				"Cartagena",
				"El Quisco",
				"El Tabo",
				"Santo Domingo",
				"San Felipe",
				"Catemu",
				"Llaillay",
				"Panquehue",
				"Putaendo",
				"Santa María",
				"Quilpué",
				"Limache",
				"Olmué",
				"Villa Alemana",
			],
		},
		{
			city: "Región del Libertador Gral. Bernardo O’Higgins",
			districts: [
				"Rancagua",
				"Codegua",
				"Coinco",
				"Coltauco",
				"Doñihue",
				"Graneros",
				"Las Cabras",
				"Machalí",
				"Malloa",
				"Mostazal",
				"Olivar",
				"Peumo",
				"Pichidegua",
				"Quinta de Tilcoco",
				"Rengo",
				"Requínoa",
				"San Vicente",
				"Pichilemu",
				"La Estrella",
				"Litueche",
				"Marchihue",
				"Navidad",
				"Paredones",
				"San Fernando",
				"Chépica",
				"Chimbarongo",
				"Lolol",
				"Nancagua",
				"Palmilla",
				"Peralillo",
				"Placilla",
				"Pumanque",
				"Santa Cruz",
			],
		},
		{
			city: "Región del Maule",
			districts: [
				"Talca",
				"Constitución",
				"Curepto",
				"Empedrado",
				"Maule",
				"Pelarco",
				"Pencahue",
				"Río Claro",
				"San Clemente",
				"San Rafael",
				"Cauquenes",
				"Chanco",
				"Pelluhue",
				"Curicó",
				"Hualañé",
				"Licantén",
				"Molina",
				"Rauco",
				"Romeral",
				"Sagrada Familia",
				"Teno",
				"Vichuquén",
				"Linares",
				"Colbún",
				"Longaví",
				"Parral",
				"Retiro",
				"San Javier",
				"Villa Alegre",
				"Yerbas Buenas",
			],
		},
		{
			city: "Región de Ñuble",
			districts: [
				"Cobquecura",
				"Coelemu",
				"Ninhue",
				"Portezuelo",
				"Quirihue",
				"Ránquil",
				"Treguaco",
				"Bulnes",
				"Chillán Viejo",
				"Chillán",
				"El Carmen",
				"Pemuco",
				"Pinto",
				"Quillón",
				"San Ignacio",
				"Yungay",
				"Coihueco",
				"Ñiquén",
				"San Carlos",
				"San Fabián",
				"San Nicolás",
			],
		},
		{
			city: "Región del Biobío",
			districts: [
				"Concepción",
				"Coronel",
				"Chiguayante",
				"Florida",
				"Hualqui",
				"Lota",
				"Penco",
				"San Pedro de la Paz",
				"Santa Juana",
				"Talcahuano",
				"Tomé",
				"Hualpén",
				"Lebu",
				"Arauco",
				"Cañete",
				"Contulmo",
				"Curanilahue",
				"Los Álamos",
				"Tirúa",
				"Los Ángeles",
				"Antuco",
				"Cabrero",
				"Laja",
				"Mulchén",
				"Nacimiento",
				"Negrete",
				"Quilaco",
				"Quilleco",
				"San Rosendo",
				"Santa Bárbara",
				"Tucapel",
				"Yumbel",
				"Alto Biobío",
			],
		},
		{
			city: "Región de la Araucanía",
			districts: [
				"Temuco",
				"Carahue",
				"Cunco",
				"Curarrehue",
				"Freire",
				"Galvarino",
				"Gorbea",
				"Lautaro",
				"Loncoche",
				"Melipeuco",
				"Nueva Imperial",
				"Padre las Casas",
				"Perquenco",
				"Pitrufquén",
				"Pucón",
				"Saavedra",
				"Teodoro Schmidt",
				"Toltén",
				"Vilcún",
				"Villarrica",
				"Cholchol",
				"Angol",
				"Collipulli",
				"Curacautín",
				"Ercilla",
				"Lonquimay",
				"Los Sauces",
				"Lumaco",
				"Purén",
				"Renaico",
				"Traiguén",
				"Victoria",
			],
		},
		{
			city: "Región de Los Ríos",
			districts: [
				"Valdivia",
				"Corral",
				"Lanco",
				"Los Lagos",
				"Máfil",
				"Mariquina",
				"Paillaco",
				"Panguipulli",
				"La Unión",
				"Futrono",
				"Lago Ranco",
				"Río Bueno",
			],
		},
		{
			city: "Región de Los Lagos",
			districts: [
				"Puerto Montt",
				"Calbuco",
				"Cochamó",
				"Fresia",
				"Frutillar",
				"Los Muermos",
				"Llanquihue",
				"Maullín",
				"Puerto Varas",
				"Castro",
				"Ancud",
				"Chonchi",
				"Curaco de Vélez",
				"Dalcahue",
				"Puqueldón",
				"Queilén",
				"Quellón",
				"Quemchi",
				"Quinchao",
				"Osorno",
				"Puerto Octay",
				"Purranque",
				"Puyehue",
				"Río Negro",
				"San Juan de la Costa",
				"San Pablo",
				"Chaitén",
				"Futaleufú",
				"Hualaihué",
				"Palena",
			],
		},
		{
			city: "Región Aisén del Gral. Carlos Ibáñez del Campo",
			districts: [
				"Coihaique",
				"Lago Verde",
				"Aisén",
				"Cisnes",
				"Guaitecas",
				"Cochrane",
				"O’Higgins",
				"Tortel",
				"Chile Chico",
				"Río Ibáñez",
			],
		},
		{
			city: "Región de Magallanes y de la Antártica Chilena",
			districts: [
				"Punta Arenas",
				"Laguna Blanca",
				"Río Verde",
				"San Gregorio",
				"Cabo de Hornos (Ex Navarino)",
				"Antártica",
				"Porvenir",
				"Primavera",
				"Timaukel",
				"Natales",
				"Torres del Paine",
			],
		},
		{
			city: "Región Metropolitana de Santiago",
			districts: [
				"Cerrillos",
				"Cerro Navia",
				"Conchalí",
				"El Bosque",
				"Estación Central",
				"Huechuraba",
				"Independencia",
				"La Cisterna",
				"La Florida",
				"La Granja",
				"La Pintana",
				"La Reina",
				"Las Condes",
				"Lo Barnechea",
				"Lo Espejo",
				"Lo Prado",
				"Macul",
				"Maipú",
				"Ñuñoa",
				"Pedro Aguirre Cerda",
				"Peñalolén",
				"Providencia",
				"Pudahuel",
				"Quilicura",
				"Quinta Normal",
				"Recoleta",
				"Renca",
				"Santiago",
				"San Joaquín",
				"San Miguel",
				"San Ramón",
				"Vitacura",
				"Puente Alto",
				"Pirque",
				"San José de Maipo",
				"Colina",
				"Lampa",
				"Tiltil",
				"San Bernardo",
				"Buin",
				"Calera de Tango",
				"Paine",
				"Melipilla",
				"Alhué",
				"Curacaví",
				"María Pinto",
				"San Pedro",
				"Talagante",
				"El Monte",
				"Isla de Maipo",
				"Padre Hurtado",
				"Peñaflor",
			],
		},
	],
};

export class SeedChileLocationsData1750137761096 implements MigrationInterface {
	public async up(queryRunner: QueryRunner): Promise<void> {
		const countryId = uuidv4();

		// Insertar país
		await queryRunner.query(`
            INSERT INTO countries (id, name) VALUES ('${countryId}', 'Chile')
        `);

		for (const region of chileData.regions) {
			const cityId = uuidv4();

			// Insertar ciudades (región)
			await queryRunner.query(
				`INSERT INTO cities (id, name, countryId) VALUES ('${cityId}', '${region.city}', '${countryId}')`,
			);

			// Insertar distritos (comunas)
			for (const district of region.districts) {
				const districtId = uuidv4();

				await queryRunner.query(
					`INSERT INTO districts (id, name, cityId) VALUES ('${districtId}', '${district}', '${cityId}')`,
				);
			}
		}
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DELETE FROM districts`);
		await queryRunner.query(`DELETE FROM cities`);
		await queryRunner.query(`DELETE FROM countries`);
	}
}
